# This is a basic workflow to help you get started with Actions

name: Prueba de Python

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
  # This workflow contains a single job called "build"
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Configurar Python
          uses: actions/setup-python@v3
          with: 
            python-version: '3.10'

      # Runs a set of commands using the runners shell
      - name: Instalar dependencias
          run: pip install -r requirements.txt
      - name: Ejecutar pruebas
          run: python -m pytest
